// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"time"
)

func (s *ApiErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/ApiError
type ApiError struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ApiError) GetCode() int32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ApiError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ApiError) SetCode(val int32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ApiError) SetMessage(val string) {
	s.Message = val
}

// ApiErrorStatusCode wraps ApiError with StatusCode.
type ApiErrorStatusCode struct {
	StatusCode int
	Response   ApiError
}

// GetStatusCode returns the value of StatusCode.
func (s *ApiErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ApiErrorStatusCode) GetResponse() ApiError {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ApiErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ApiErrorStatusCode) SetResponse(val ApiError) {
	s.Response = val
}

// Ref: #/components/schemas/AuthResponse
type AuthResponse struct {
	// JWT access token issued by this server.
	AccessToken string `json:"accessToken"`
	// Authenticated user info.
	User UserProfile `json:"user"`
}

// GetAccessToken returns the value of AccessToken.
func (s *AuthResponse) GetAccessToken() string {
	return s.AccessToken
}

// GetUser returns the value of User.
func (s *AuthResponse) GetUser() UserProfile {
	return s.User
}

// SetAccessToken sets the value of AccessToken.
func (s *AuthResponse) SetAccessToken(val string) {
	s.AccessToken = val
}

// SetUser sets the value of User.
func (s *AuthResponse) SetUser(val UserProfile) {
	s.User = val
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/CreatePriorityRequest
type CreatePriorityRequest struct {
	Name         string `json:"name"`
	DisplayOrder int32  `json:"displayOrder"`
}

// GetName returns the value of Name.
func (s *CreatePriorityRequest) GetName() string {
	return s.Name
}

// GetDisplayOrder returns the value of DisplayOrder.
func (s *CreatePriorityRequest) GetDisplayOrder() int32 {
	return s.DisplayOrder
}

// SetName sets the value of Name.
func (s *CreatePriorityRequest) SetName(val string) {
	s.Name = val
}

// SetDisplayOrder sets the value of DisplayOrder.
func (s *CreatePriorityRequest) SetDisplayOrder(val int32) {
	s.DisplayOrder = val
}

// Ref: #/components/schemas/CreateStatusRequest
type CreateStatusRequest struct {
	Name         string `json:"name"`
	DisplayOrder int32  `json:"displayOrder"`
}

// GetName returns the value of Name.
func (s *CreateStatusRequest) GetName() string {
	return s.Name
}

// GetDisplayOrder returns the value of DisplayOrder.
func (s *CreateStatusRequest) GetDisplayOrder() int32 {
	return s.DisplayOrder
}

// SetName sets the value of Name.
func (s *CreateStatusRequest) SetName(val string) {
	s.Name = val
}

// SetDisplayOrder sets the value of DisplayOrder.
func (s *CreateStatusRequest) SetDisplayOrder(val int32) {
	s.DisplayOrder = val
}

// Ref: #/components/schemas/CreateTagRequest
type CreateTagRequest struct {
	Name string `json:"name"`
}

// GetName returns the value of Name.
func (s *CreateTagRequest) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *CreateTagRequest) SetName(val string) {
	s.Name = val
}

// Ref: #/components/schemas/CreateTaskRequest
type CreateTaskRequest struct {
	Title      string      `json:"title"`
	Memo       OptString   `json:"memo"`
	DueDate    OptDateTime `json:"dueDate"`
	StatusId   string      `json:"statusId"`
	PriorityId OptString   `json:"priorityId"`
	TagIds     []string    `json:"tagIds"`
}

// GetTitle returns the value of Title.
func (s *CreateTaskRequest) GetTitle() string {
	return s.Title
}

// GetMemo returns the value of Memo.
func (s *CreateTaskRequest) GetMemo() OptString {
	return s.Memo
}

// GetDueDate returns the value of DueDate.
func (s *CreateTaskRequest) GetDueDate() OptDateTime {
	return s.DueDate
}

// GetStatusId returns the value of StatusId.
func (s *CreateTaskRequest) GetStatusId() string {
	return s.StatusId
}

// GetPriorityId returns the value of PriorityId.
func (s *CreateTaskRequest) GetPriorityId() OptString {
	return s.PriorityId
}

// GetTagIds returns the value of TagIds.
func (s *CreateTaskRequest) GetTagIds() []string {
	return s.TagIds
}

// SetTitle sets the value of Title.
func (s *CreateTaskRequest) SetTitle(val string) {
	s.Title = val
}

// SetMemo sets the value of Memo.
func (s *CreateTaskRequest) SetMemo(val OptString) {
	s.Memo = val
}

// SetDueDate sets the value of DueDate.
func (s *CreateTaskRequest) SetDueDate(val OptDateTime) {
	s.DueDate = val
}

// SetStatusId sets the value of StatusId.
func (s *CreateTaskRequest) SetStatusId(val string) {
	s.StatusId = val
}

// SetPriorityId sets the value of PriorityId.
func (s *CreateTaskRequest) SetPriorityId(val OptString) {
	s.PriorityId = val
}

// SetTagIds sets the value of TagIds.
func (s *CreateTaskRequest) SetTagIds(val []string) {
	s.TagIds = val
}

// Ref: #/components/schemas/GoogleAuthCodeRequest
type GoogleAuthCodeRequest struct {
	// Authorization code from OAuth2 redirect.
	Code string `json:"code"`
	// Redirect URI used in the OAuth2 flow (must match).
	RedirectUri string `json:"redirectUri"`
}

// GetCode returns the value of Code.
func (s *GoogleAuthCodeRequest) GetCode() string {
	return s.Code
}

// GetRedirectUri returns the value of RedirectUri.
func (s *GoogleAuthCodeRequest) GetRedirectUri() string {
	return s.RedirectUri
}

// SetCode sets the value of Code.
func (s *GoogleAuthCodeRequest) SetCode(val string) {
	s.Code = val
}

// SetRedirectUri sets the value of RedirectUri.
func (s *GoogleAuthCodeRequest) SetRedirectUri(val string) {
	s.RedirectUri = val
}

// Ref: #/components/schemas/GoogleAuthRequest
type GoogleAuthRequest struct {
	// Google ID token obtained from Google Sign-In.
	IdToken string `json:"idToken"`
}

// GetIdToken returns the value of IdToken.
func (s *GoogleAuthRequest) GetIdToken() string {
	return s.IdToken
}

// SetIdToken sets the value of IdToken.
func (s *GoogleAuthRequest) SetIdToken(val string) {
	s.IdToken = val
}

// NewNilDateTime returns new NilDateTime with value set to v.
func NewNilDateTime(v time.Time) NilDateTime {
	return NilDateTime{
		Value: v,
	}
}

// NilDateTime is nullable time.Time.
type NilDateTime struct {
	Value time.Time
	Null  bool
}

// SetTo sets value to v.
func (o *NilDateTime) SetTo(v time.Time) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilDateTime) SetToNull() {
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewNilString returns new NilString with value set to v.
func NewNilString(v string) NilString {
	return NilString{
		Value: v,
	}
}

// NilString is nullable string.
type NilString struct {
	Value string
	Null  bool
}

// SetTo sets value to v.
func (o *NilString) SetTo(v string) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilString) SetToNull() {
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDateTime returns new OptNilDateTime with value set to v.
func NewOptNilDateTime(v time.Time) OptNilDateTime {
	return OptNilDateTime{
		Value: v,
		Set:   true,
	}
}

// OptNilDateTime is optional nullable time.Time.
type OptNilDateTime struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDateTime was set.
func (o OptNilDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDateTime) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Priority
type Priority struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	DisplayOrder int32  `json:"displayOrder"`
}

// GetID returns the value of ID.
func (s *Priority) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *Priority) GetName() string {
	return s.Name
}

// GetDisplayOrder returns the value of DisplayOrder.
func (s *Priority) GetDisplayOrder() int32 {
	return s.DisplayOrder
}

// SetID sets the value of ID.
func (s *Priority) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Priority) SetName(val string) {
	s.Name = val
}

// SetDisplayOrder sets the value of DisplayOrder.
func (s *Priority) SetDisplayOrder(val int32) {
	s.DisplayOrder = val
}

// Ref: #/components/schemas/PriorityList
type PriorityList struct {
	Items []Priority `json:"items"`
}

// GetItems returns the value of Items.
func (s *PriorityList) GetItems() []Priority {
	return s.Items
}

// SetItems sets the value of Items.
func (s *PriorityList) SetItems(val []Priority) {
	s.Items = val
}

// PriorityOpsDeleteNoContent is response for PriorityOpsDelete operation.
type PriorityOpsDeleteNoContent struct{}

// Ref: #/components/schemas/Status
type Status struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	DisplayOrder int32  `json:"displayOrder"`
}

// GetID returns the value of ID.
func (s *Status) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *Status) GetName() string {
	return s.Name
}

// GetDisplayOrder returns the value of DisplayOrder.
func (s *Status) GetDisplayOrder() int32 {
	return s.DisplayOrder
}

// SetID sets the value of ID.
func (s *Status) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Status) SetName(val string) {
	s.Name = val
}

// SetDisplayOrder sets the value of DisplayOrder.
func (s *Status) SetDisplayOrder(val int32) {
	s.DisplayOrder = val
}

// Ref: #/components/schemas/StatusList
type StatusList struct {
	Items []Status `json:"items"`
}

// GetItems returns the value of Items.
func (s *StatusList) GetItems() []Status {
	return s.Items
}

// SetItems sets the value of Items.
func (s *StatusList) SetItems(val []Status) {
	s.Items = val
}

// StatusOpsDeleteNoContent is response for StatusOpsDelete operation.
type StatusOpsDeleteNoContent struct{}

// Ref: #/components/schemas/Tag
type Tag struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// GetID returns the value of ID.
func (s *Tag) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *Tag) GetName() string {
	return s.Name
}

// SetID sets the value of ID.
func (s *Tag) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Tag) SetName(val string) {
	s.Name = val
}

// Ref: #/components/schemas/TagList
type TagList struct {
	Items []Tag `json:"items"`
}

// GetItems returns the value of Items.
func (s *TagList) GetItems() []Tag {
	return s.Items
}

// SetItems sets the value of Items.
func (s *TagList) SetItems(val []Tag) {
	s.Items = val
}

// TagOpsDeleteNoContent is response for TagOpsDelete operation.
type TagOpsDeleteNoContent struct{}

// Ref: #/components/schemas/Task
type Task struct {
	ID         string      `json:"id"`
	Title      string      `json:"title"`
	Memo       NilString   `json:"memo"`
	DueDate    NilDateTime `json:"dueDate"`
	StatusId   string      `json:"statusId"`
	PriorityId NilString   `json:"priorityId"`
	TagIds     []string    `json:"tagIds"`
	CreatedAt  time.Time   `json:"createdAt"`
	UpdatedAt  time.Time   `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *Task) GetID() string {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *Task) GetTitle() string {
	return s.Title
}

// GetMemo returns the value of Memo.
func (s *Task) GetMemo() NilString {
	return s.Memo
}

// GetDueDate returns the value of DueDate.
func (s *Task) GetDueDate() NilDateTime {
	return s.DueDate
}

// GetStatusId returns the value of StatusId.
func (s *Task) GetStatusId() string {
	return s.StatusId
}

// GetPriorityId returns the value of PriorityId.
func (s *Task) GetPriorityId() NilString {
	return s.PriorityId
}

// GetTagIds returns the value of TagIds.
func (s *Task) GetTagIds() []string {
	return s.TagIds
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Task) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Task) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Task) SetID(val string) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *Task) SetTitle(val string) {
	s.Title = val
}

// SetMemo sets the value of Memo.
func (s *Task) SetMemo(val NilString) {
	s.Memo = val
}

// SetDueDate sets the value of DueDate.
func (s *Task) SetDueDate(val NilDateTime) {
	s.DueDate = val
}

// SetStatusId sets the value of StatusId.
func (s *Task) SetStatusId(val string) {
	s.StatusId = val
}

// SetPriorityId sets the value of PriorityId.
func (s *Task) SetPriorityId(val NilString) {
	s.PriorityId = val
}

// SetTagIds sets the value of TagIds.
func (s *Task) SetTagIds(val []string) {
	s.TagIds = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Task) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Task) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// Ref: #/components/schemas/TaskList
type TaskList struct {
	Items []Task `json:"items"`
}

// GetItems returns the value of Items.
func (s *TaskList) GetItems() []Task {
	return s.Items
}

// SetItems sets the value of Items.
func (s *TaskList) SetItems(val []Task) {
	s.Items = val
}

// TaskOpsDeleteNoContent is response for TaskOpsDelete operation.
type TaskOpsDeleteNoContent struct{}

// Ref: #/components/schemas/UpdatePriorityRequest
type UpdatePriorityRequest struct {
	Name         OptString `json:"name"`
	DisplayOrder OptInt32  `json:"displayOrder"`
}

// GetName returns the value of Name.
func (s *UpdatePriorityRequest) GetName() OptString {
	return s.Name
}

// GetDisplayOrder returns the value of DisplayOrder.
func (s *UpdatePriorityRequest) GetDisplayOrder() OptInt32 {
	return s.DisplayOrder
}

// SetName sets the value of Name.
func (s *UpdatePriorityRequest) SetName(val OptString) {
	s.Name = val
}

// SetDisplayOrder sets the value of DisplayOrder.
func (s *UpdatePriorityRequest) SetDisplayOrder(val OptInt32) {
	s.DisplayOrder = val
}

// Ref: #/components/schemas/UpdateStatusRequest
type UpdateStatusRequest struct {
	Name         OptString `json:"name"`
	DisplayOrder OptInt32  `json:"displayOrder"`
}

// GetName returns the value of Name.
func (s *UpdateStatusRequest) GetName() OptString {
	return s.Name
}

// GetDisplayOrder returns the value of DisplayOrder.
func (s *UpdateStatusRequest) GetDisplayOrder() OptInt32 {
	return s.DisplayOrder
}

// SetName sets the value of Name.
func (s *UpdateStatusRequest) SetName(val OptString) {
	s.Name = val
}

// SetDisplayOrder sets the value of DisplayOrder.
func (s *UpdateStatusRequest) SetDisplayOrder(val OptInt32) {
	s.DisplayOrder = val
}

// Ref: #/components/schemas/UpdateTagRequest
type UpdateTagRequest struct {
	Name OptString `json:"name"`
}

// GetName returns the value of Name.
func (s *UpdateTagRequest) GetName() OptString {
	return s.Name
}

// SetName sets the value of Name.
func (s *UpdateTagRequest) SetName(val OptString) {
	s.Name = val
}

// Ref: #/components/schemas/UpdateTaskRequest
type UpdateTaskRequest struct {
	Title      OptString      `json:"title"`
	Memo       OptNilString   `json:"memo"`
	DueDate    OptNilDateTime `json:"dueDate"`
	StatusId   OptString      `json:"statusId"`
	PriorityId OptNilString   `json:"priorityId"`
	TagIds     []string       `json:"tagIds"`
}

// GetTitle returns the value of Title.
func (s *UpdateTaskRequest) GetTitle() OptString {
	return s.Title
}

// GetMemo returns the value of Memo.
func (s *UpdateTaskRequest) GetMemo() OptNilString {
	return s.Memo
}

// GetDueDate returns the value of DueDate.
func (s *UpdateTaskRequest) GetDueDate() OptNilDateTime {
	return s.DueDate
}

// GetStatusId returns the value of StatusId.
func (s *UpdateTaskRequest) GetStatusId() OptString {
	return s.StatusId
}

// GetPriorityId returns the value of PriorityId.
func (s *UpdateTaskRequest) GetPriorityId() OptNilString {
	return s.PriorityId
}

// GetTagIds returns the value of TagIds.
func (s *UpdateTaskRequest) GetTagIds() []string {
	return s.TagIds
}

// SetTitle sets the value of Title.
func (s *UpdateTaskRequest) SetTitle(val OptString) {
	s.Title = val
}

// SetMemo sets the value of Memo.
func (s *UpdateTaskRequest) SetMemo(val OptNilString) {
	s.Memo = val
}

// SetDueDate sets the value of DueDate.
func (s *UpdateTaskRequest) SetDueDate(val OptNilDateTime) {
	s.DueDate = val
}

// SetStatusId sets the value of StatusId.
func (s *UpdateTaskRequest) SetStatusId(val OptString) {
	s.StatusId = val
}

// SetPriorityId sets the value of PriorityId.
func (s *UpdateTaskRequest) SetPriorityId(val OptNilString) {
	s.PriorityId = val
}

// SetTagIds sets the value of TagIds.
func (s *UpdateTaskRequest) SetTagIds(val []string) {
	s.TagIds = val
}

// Ref: #/components/schemas/UserProfile
type UserProfile struct {
	ID          string    `json:"id"`
	Email       string    `json:"email"`
	DisplayName string    `json:"displayName"`
	AvatarUrl   NilString `json:"avatarUrl"`
}

// GetID returns the value of ID.
func (s *UserProfile) GetID() string {
	return s.ID
}

// GetEmail returns the value of Email.
func (s *UserProfile) GetEmail() string {
	return s.Email
}

// GetDisplayName returns the value of DisplayName.
func (s *UserProfile) GetDisplayName() string {
	return s.DisplayName
}

// GetAvatarUrl returns the value of AvatarUrl.
func (s *UserProfile) GetAvatarUrl() NilString {
	return s.AvatarUrl
}

// SetID sets the value of ID.
func (s *UserProfile) SetID(val string) {
	s.ID = val
}

// SetEmail sets the value of Email.
func (s *UserProfile) SetEmail(val string) {
	s.Email = val
}

// SetDisplayName sets the value of DisplayName.
func (s *UserProfile) SetDisplayName(val string) {
	s.DisplayName = val
}

// SetAvatarUrl sets the value of AvatarUrl.
func (s *UserProfile) SetAvatarUrl(val NilString) {
	s.AvatarUrl = val
}
