// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

var (
	rn3AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn4AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn1AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn8AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn10AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
		"PATCH":  "Authorization,Content-Type",
	}
	rn11AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn13AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
		"PATCH":  "Authorization,Content-Type",
	}
	rn14AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn16AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
		"PATCH":  "Authorization,Content-Type",
	}
	rn18AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn20AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
		"GET":    "Authorization",
		"PATCH":  "Authorization,Content-Type",
	}
	rn21AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn23AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
		"PUT":    "Authorization,Content-Type",
	}
	rn25AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn27AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
		"GET":    "Authorization",
		"PUT":    "Authorization,Content-Type",
	}
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [1]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "auth/"

				if l := len("auth/"); len(elem) >= l && elem[0:l] == "auth/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'g': // Prefix: "google"

					if l := len("google"); len(elem) >= l && elem[0:l] == "google" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "POST":
							s.handleAuthOpsGoogleLoginRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "POST",
								allowedHeaders: rn3AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/code"

						if l := len("/code"); len(elem) >= l && elem[0:l] == "/code" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleAuthOpsGoogleLoginWithCodeRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn4AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				case 'm': // Prefix: "me"

					if l := len("me"); len(elem) >= l && elem[0:l] == "me" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleAuthOpsGetMeRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: rn1AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			case 'p': // Prefix: "p"

				if l := len("p"); len(elem) >= l && elem[0:l] == "p" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'i': // Prefix: "ing"

					if l := len("ing"); len(elem) >= l && elem[0:l] == "ing" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleHealthOpsPingRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: nil,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				case 'r': // Prefix: "riorities"

					if l := len("riorities"); len(elem) >= l && elem[0:l] == "riorities" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handlePriorityOpsListRequest([0]string{}, elemIsEscaped, w, r)
						case "POST":
							s.handlePriorityOpsCreateRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,POST",
								allowedHeaders: rn8AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "DELETE":
								s.handlePriorityOpsDeleteRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "PATCH":
								s.handlePriorityOpsUpdateRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "DELETE,PATCH",
									allowedHeaders: rn10AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "application/json",
								})
							}

							return
						}

					}

				}

			case 's': // Prefix: "statuses"

				if l := len("statuses"); len(elem) >= l && elem[0:l] == "statuses" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleStatusOpsListRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleStatusOpsCreateRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET,POST",
							allowedHeaders: rn11AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "DELETE":
							s.handleStatusOpsDeleteRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PATCH":
							s.handleStatusOpsUpdateRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "DELETE,PATCH",
								allowedHeaders: rn13AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "application/json",
							})
						}

						return
					}

				}

			case 't': // Prefix: "ta"

				if l := len("ta"); len(elem) >= l && elem[0:l] == "ta" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'g': // Prefix: "gs"

					if l := len("gs"); len(elem) >= l && elem[0:l] == "gs" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleTagOpsListRequest([0]string{}, elemIsEscaped, w, r)
						case "POST":
							s.handleTagOpsCreateRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,POST",
								allowedHeaders: rn14AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "DELETE":
								s.handleTagOpsDeleteRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "PATCH":
								s.handleTagOpsUpdateRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "DELETE,PATCH",
									allowedHeaders: rn16AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "application/json",
								})
							}

							return
						}

					}

				case 's': // Prefix: "sks"

					if l := len("sks"); len(elem) >= l && elem[0:l] == "sks" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleTaskOpsListRequest([0]string{}, elemIsEscaped, w, r)
						case "POST":
							s.handleTaskOpsCreateRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,POST",
								allowedHeaders: rn18AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "DELETE":
								s.handleTaskOpsDeleteRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "GET":
								s.handleTaskOpsGetRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "PATCH":
								s.handleTaskOpsUpdateRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "DELETE,GET,PATCH",
									allowedHeaders: rn20AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "application/json",
								})
							}

							return
						}

					}

				}

			case 'w': // Prefix: "wish"

				if l := len("wish"); len(elem) >= l && elem[0:l] == "wish" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '-': // Prefix: "-labels"

					if l := len("-labels"); len(elem) >= l && elem[0:l] == "-labels" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleWishLabelOpsListRequest([0]string{}, elemIsEscaped, w, r)
						case "POST":
							s.handleWishLabelOpsCreateRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,POST",
								allowedHeaders: rn21AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "DELETE":
								s.handleWishLabelOpsDeleteRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "PUT":
								s.handleWishLabelOpsUpdateRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "DELETE,PUT",
									allowedHeaders: rn23AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				case 'e': // Prefix: "es"

					if l := len("es"); len(elem) >= l && elem[0:l] == "es" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleWishOpsListRequest([0]string{}, elemIsEscaped, w, r)
						case "POST":
							s.handleWishOpsCreateRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,POST",
								allowedHeaders: rn25AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "DELETE":
								s.handleWishOpsDeleteRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "GET":
								s.handleWishOpsGetRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "PUT":
								s.handleWishOpsUpdateRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "DELETE,GET,PUT",
									allowedHeaders: rn27AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [1]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "auth/"

				if l := len("auth/"); len(elem) >= l && elem[0:l] == "auth/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'g': // Prefix: "google"

					if l := len("google"); len(elem) >= l && elem[0:l] == "google" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "POST":
							r.name = AuthOpsGoogleLoginOperation
							r.summary = ""
							r.operationID = "AuthOps_googleLogin"
							r.operationGroup = ""
							r.pathPattern = "/auth/google"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/code"

						if l := len("/code"); len(elem) >= l && elem[0:l] == "/code" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = AuthOpsGoogleLoginWithCodeOperation
								r.summary = ""
								r.operationID = "AuthOps_googleLoginWithCode"
								r.operationGroup = ""
								r.pathPattern = "/auth/google/code"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					}

				case 'm': // Prefix: "me"

					if l := len("me"); len(elem) >= l && elem[0:l] == "me" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = AuthOpsGetMeOperation
							r.summary = ""
							r.operationID = "AuthOps_getMe"
							r.operationGroup = ""
							r.pathPattern = "/auth/me"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				}

			case 'p': // Prefix: "p"

				if l := len("p"); len(elem) >= l && elem[0:l] == "p" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'i': // Prefix: "ing"

					if l := len("ing"); len(elem) >= l && elem[0:l] == "ing" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = HealthOpsPingOperation
							r.summary = ""
							r.operationID = "HealthOps_ping"
							r.operationGroup = ""
							r.pathPattern = "/ping"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 'r': // Prefix: "riorities"

					if l := len("riorities"); len(elem) >= l && elem[0:l] == "riorities" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = PriorityOpsListOperation
							r.summary = ""
							r.operationID = "PriorityOps_list"
							r.operationGroup = ""
							r.pathPattern = "/priorities"
							r.args = args
							r.count = 0
							return r, true
						case "POST":
							r.name = PriorityOpsCreateOperation
							r.summary = ""
							r.operationID = "PriorityOps_create"
							r.operationGroup = ""
							r.pathPattern = "/priorities"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "DELETE":
								r.name = PriorityOpsDeleteOperation
								r.summary = ""
								r.operationID = "PriorityOps_delete"
								r.operationGroup = ""
								r.pathPattern = "/priorities/{id}"
								r.args = args
								r.count = 1
								return r, true
							case "PATCH":
								r.name = PriorityOpsUpdateOperation
								r.summary = ""
								r.operationID = "PriorityOps_update"
								r.operationGroup = ""
								r.pathPattern = "/priorities/{id}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				}

			case 's': // Prefix: "statuses"

				if l := len("statuses"); len(elem) >= l && elem[0:l] == "statuses" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = StatusOpsListOperation
						r.summary = ""
						r.operationID = "StatusOps_list"
						r.operationGroup = ""
						r.pathPattern = "/statuses"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = StatusOpsCreateOperation
						r.summary = ""
						r.operationID = "StatusOps_create"
						r.operationGroup = ""
						r.pathPattern = "/statuses"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "DELETE":
							r.name = StatusOpsDeleteOperation
							r.summary = ""
							r.operationID = "StatusOps_delete"
							r.operationGroup = ""
							r.pathPattern = "/statuses/{id}"
							r.args = args
							r.count = 1
							return r, true
						case "PATCH":
							r.name = StatusOpsUpdateOperation
							r.summary = ""
							r.operationID = "StatusOps_update"
							r.operationGroup = ""
							r.pathPattern = "/statuses/{id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

				}

			case 't': // Prefix: "ta"

				if l := len("ta"); len(elem) >= l && elem[0:l] == "ta" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'g': // Prefix: "gs"

					if l := len("gs"); len(elem) >= l && elem[0:l] == "gs" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = TagOpsListOperation
							r.summary = ""
							r.operationID = "TagOps_list"
							r.operationGroup = ""
							r.pathPattern = "/tags"
							r.args = args
							r.count = 0
							return r, true
						case "POST":
							r.name = TagOpsCreateOperation
							r.summary = ""
							r.operationID = "TagOps_create"
							r.operationGroup = ""
							r.pathPattern = "/tags"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "DELETE":
								r.name = TagOpsDeleteOperation
								r.summary = ""
								r.operationID = "TagOps_delete"
								r.operationGroup = ""
								r.pathPattern = "/tags/{id}"
								r.args = args
								r.count = 1
								return r, true
							case "PATCH":
								r.name = TagOpsUpdateOperation
								r.summary = ""
								r.operationID = "TagOps_update"
								r.operationGroup = ""
								r.pathPattern = "/tags/{id}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				case 's': // Prefix: "sks"

					if l := len("sks"); len(elem) >= l && elem[0:l] == "sks" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = TaskOpsListOperation
							r.summary = ""
							r.operationID = "TaskOps_list"
							r.operationGroup = ""
							r.pathPattern = "/tasks"
							r.args = args
							r.count = 0
							return r, true
						case "POST":
							r.name = TaskOpsCreateOperation
							r.summary = ""
							r.operationID = "TaskOps_create"
							r.operationGroup = ""
							r.pathPattern = "/tasks"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "DELETE":
								r.name = TaskOpsDeleteOperation
								r.summary = ""
								r.operationID = "TaskOps_delete"
								r.operationGroup = ""
								r.pathPattern = "/tasks/{id}"
								r.args = args
								r.count = 1
								return r, true
							case "GET":
								r.name = TaskOpsGetOperation
								r.summary = ""
								r.operationID = "TaskOps_get"
								r.operationGroup = ""
								r.pathPattern = "/tasks/{id}"
								r.args = args
								r.count = 1
								return r, true
							case "PATCH":
								r.name = TaskOpsUpdateOperation
								r.summary = ""
								r.operationID = "TaskOps_update"
								r.operationGroup = ""
								r.pathPattern = "/tasks/{id}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				}

			case 'w': // Prefix: "wish"

				if l := len("wish"); len(elem) >= l && elem[0:l] == "wish" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '-': // Prefix: "-labels"

					if l := len("-labels"); len(elem) >= l && elem[0:l] == "-labels" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = WishLabelOpsListOperation
							r.summary = ""
							r.operationID = "WishLabelOps_list"
							r.operationGroup = ""
							r.pathPattern = "/wish-labels"
							r.args = args
							r.count = 0
							return r, true
						case "POST":
							r.name = WishLabelOpsCreateOperation
							r.summary = ""
							r.operationID = "WishLabelOps_create"
							r.operationGroup = ""
							r.pathPattern = "/wish-labels"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "DELETE":
								r.name = WishLabelOpsDeleteOperation
								r.summary = ""
								r.operationID = "WishLabelOps_delete"
								r.operationGroup = ""
								r.pathPattern = "/wish-labels/{id}"
								r.args = args
								r.count = 1
								return r, true
							case "PUT":
								r.name = WishLabelOpsUpdateOperation
								r.summary = ""
								r.operationID = "WishLabelOps_update"
								r.operationGroup = ""
								r.pathPattern = "/wish-labels/{id}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				case 'e': // Prefix: "es"

					if l := len("es"); len(elem) >= l && elem[0:l] == "es" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = WishOpsListOperation
							r.summary = ""
							r.operationID = "WishOps_list"
							r.operationGroup = ""
							r.pathPattern = "/wishes"
							r.args = args
							r.count = 0
							return r, true
						case "POST":
							r.name = WishOpsCreateOperation
							r.summary = ""
							r.operationID = "WishOps_create"
							r.operationGroup = ""
							r.pathPattern = "/wishes"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "DELETE":
								r.name = WishOpsDeleteOperation
								r.summary = ""
								r.operationID = "WishOps_delete"
								r.operationGroup = ""
								r.pathPattern = "/wishes/{id}"
								r.args = args
								r.count = 1
								return r, true
							case "GET":
								r.name = WishOpsGetOperation
								r.summary = ""
								r.operationID = "WishOps_get"
								r.operationGroup = ""
								r.pathPattern = "/wishes/{id}"
								r.args = args
								r.count = 1
								return r, true
							case "PUT":
								r.name = WishOpsUpdateOperation
								r.summary = ""
								r.operationID = "WishOps_update"
								r.operationGroup = ""
								r.pathPattern = "/wishes/{id}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				}

			}

		}
	}
	return r, false
}
