// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AuthOpsGetMe implements AuthOps_getMe operation.
//
// Get the currently authenticated user.
//
// GET /auth/me
func (UnimplementedHandler) AuthOpsGetMe(ctx context.Context) (r *UserProfile, _ error) {
	return r, ht.ErrNotImplemented
}

// AuthOpsGoogleLogin implements AuthOps_googleLogin operation.
//
// Exchange Google ID token for a server-issued JWT.
//
// POST /auth/google
func (UnimplementedHandler) AuthOpsGoogleLogin(ctx context.Context, req *GoogleAuthRequest) (r *AuthResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// PriorityOpsCreate implements PriorityOps_create operation.
//
// POST /priorities
func (UnimplementedHandler) PriorityOpsCreate(ctx context.Context, req *CreatePriorityRequest) (r *Priority, _ error) {
	return r, ht.ErrNotImplemented
}

// PriorityOpsDelete implements PriorityOps_delete operation.
//
// DELETE /priorities/{id}
func (UnimplementedHandler) PriorityOpsDelete(ctx context.Context, params PriorityOpsDeleteParams) error {
	return ht.ErrNotImplemented
}

// PriorityOpsList implements PriorityOps_list operation.
//
// GET /priorities
func (UnimplementedHandler) PriorityOpsList(ctx context.Context) (r *PriorityList, _ error) {
	return r, ht.ErrNotImplemented
}

// PriorityOpsUpdate implements PriorityOps_update operation.
//
// PATCH /priorities/{id}
func (UnimplementedHandler) PriorityOpsUpdate(ctx context.Context, req *UpdatePriorityRequest, params PriorityOpsUpdateParams) (r *Priority, _ error) {
	return r, ht.ErrNotImplemented
}

// StatusOpsCreate implements StatusOps_create operation.
//
// POST /statuses
func (UnimplementedHandler) StatusOpsCreate(ctx context.Context, req *CreateStatusRequest) (r *Status, _ error) {
	return r, ht.ErrNotImplemented
}

// StatusOpsDelete implements StatusOps_delete operation.
//
// DELETE /statuses/{id}
func (UnimplementedHandler) StatusOpsDelete(ctx context.Context, params StatusOpsDeleteParams) error {
	return ht.ErrNotImplemented
}

// StatusOpsList implements StatusOps_list operation.
//
// GET /statuses
func (UnimplementedHandler) StatusOpsList(ctx context.Context) (r *StatusList, _ error) {
	return r, ht.ErrNotImplemented
}

// StatusOpsUpdate implements StatusOps_update operation.
//
// PATCH /statuses/{id}
func (UnimplementedHandler) StatusOpsUpdate(ctx context.Context, req *UpdateStatusRequest, params StatusOpsUpdateParams) (r *Status, _ error) {
	return r, ht.ErrNotImplemented
}

// TagOpsCreate implements TagOps_create operation.
//
// POST /tags
func (UnimplementedHandler) TagOpsCreate(ctx context.Context, req *CreateTagRequest) (r *Tag, _ error) {
	return r, ht.ErrNotImplemented
}

// TagOpsDelete implements TagOps_delete operation.
//
// DELETE /tags/{id}
func (UnimplementedHandler) TagOpsDelete(ctx context.Context, params TagOpsDeleteParams) error {
	return ht.ErrNotImplemented
}

// TagOpsList implements TagOps_list operation.
//
// GET /tags
func (UnimplementedHandler) TagOpsList(ctx context.Context) (r *TagList, _ error) {
	return r, ht.ErrNotImplemented
}

// TagOpsUpdate implements TagOps_update operation.
//
// PATCH /tags/{id}
func (UnimplementedHandler) TagOpsUpdate(ctx context.Context, req *UpdateTagRequest, params TagOpsUpdateParams) (r *Tag, _ error) {
	return r, ht.ErrNotImplemented
}

// TaskOpsCreate implements TaskOps_create operation.
//
// Create a new task.
//
// POST /tasks
func (UnimplementedHandler) TaskOpsCreate(ctx context.Context, req *CreateTaskRequest) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}

// TaskOpsDelete implements TaskOps_delete operation.
//
// Delete a task.
//
// DELETE /tasks/{id}
func (UnimplementedHandler) TaskOpsDelete(ctx context.Context, params TaskOpsDeleteParams) error {
	return ht.ErrNotImplemented
}

// TaskOpsGet implements TaskOps_get operation.
//
// Get a task by ID.
//
// GET /tasks/{id}
func (UnimplementedHandler) TaskOpsGet(ctx context.Context, params TaskOpsGetParams) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}

// TaskOpsList implements TaskOps_list operation.
//
// List all tasks for the authenticated user.
//
// GET /tasks
func (UnimplementedHandler) TaskOpsList(ctx context.Context) (r *TaskList, _ error) {
	return r, ht.ErrNotImplemented
}

// TaskOpsUpdate implements TaskOps_update operation.
//
// Update a task.
//
// PATCH /tasks/{id}
func (UnimplementedHandler) TaskOpsUpdate(ctx context.Context, req *UpdateTaskRequest, params TaskOpsUpdateParams) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ApiErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ApiErrorStatusCode) {
	r = new(ApiErrorStatusCode)
	return r
}
