// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AuthOpsGetMe implements AuthOps_getMe operation.
	//
	// Get the currently authenticated user.
	//
	// GET /auth/me
	AuthOpsGetMe(ctx context.Context) (*UserProfile, error)
	// AuthOpsGoogleLogin implements AuthOps_googleLogin operation.
	//
	// Exchange Google ID token for a server-issued JWT.
	//
	// POST /auth/google
	AuthOpsGoogleLogin(ctx context.Context, req *GoogleAuthRequest) (*AuthResponse, error)
	// AuthOpsGoogleLoginWithCode implements AuthOps_googleLoginWithCode operation.
	//
	// Exchange Google authorization code for a server-issued JWT.
	//
	// POST /auth/google/code
	AuthOpsGoogleLoginWithCode(ctx context.Context, req *GoogleAuthCodeRequest) (*AuthResponse, error)
	// PriorityOpsCreate implements PriorityOps_create operation.
	//
	// POST /priorities
	PriorityOpsCreate(ctx context.Context, req *CreatePriorityRequest) (*Priority, error)
	// PriorityOpsDelete implements PriorityOps_delete operation.
	//
	// DELETE /priorities/{id}
	PriorityOpsDelete(ctx context.Context, params PriorityOpsDeleteParams) error
	// PriorityOpsList implements PriorityOps_list operation.
	//
	// GET /priorities
	PriorityOpsList(ctx context.Context) (*PriorityList, error)
	// PriorityOpsUpdate implements PriorityOps_update operation.
	//
	// PATCH /priorities/{id}
	PriorityOpsUpdate(ctx context.Context, req *UpdatePriorityRequest, params PriorityOpsUpdateParams) (*Priority, error)
	// StatusOpsCreate implements StatusOps_create operation.
	//
	// POST /statuses
	StatusOpsCreate(ctx context.Context, req *CreateStatusRequest) (*Status, error)
	// StatusOpsDelete implements StatusOps_delete operation.
	//
	// DELETE /statuses/{id}
	StatusOpsDelete(ctx context.Context, params StatusOpsDeleteParams) error
	// StatusOpsList implements StatusOps_list operation.
	//
	// GET /statuses
	StatusOpsList(ctx context.Context) (*StatusList, error)
	// StatusOpsUpdate implements StatusOps_update operation.
	//
	// PATCH /statuses/{id}
	StatusOpsUpdate(ctx context.Context, req *UpdateStatusRequest, params StatusOpsUpdateParams) (*Status, error)
	// TagOpsCreate implements TagOps_create operation.
	//
	// POST /tags
	TagOpsCreate(ctx context.Context, req *CreateTagRequest) (*Tag, error)
	// TagOpsDelete implements TagOps_delete operation.
	//
	// DELETE /tags/{id}
	TagOpsDelete(ctx context.Context, params TagOpsDeleteParams) error
	// TagOpsList implements TagOps_list operation.
	//
	// GET /tags
	TagOpsList(ctx context.Context) (*TagList, error)
	// TagOpsUpdate implements TagOps_update operation.
	//
	// PATCH /tags/{id}
	TagOpsUpdate(ctx context.Context, req *UpdateTagRequest, params TagOpsUpdateParams) (*Tag, error)
	// TaskOpsCreate implements TaskOps_create operation.
	//
	// Create a new task.
	//
	// POST /tasks
	TaskOpsCreate(ctx context.Context, req *CreateTaskRequest) (*Task, error)
	// TaskOpsDelete implements TaskOps_delete operation.
	//
	// Delete a task.
	//
	// DELETE /tasks/{id}
	TaskOpsDelete(ctx context.Context, params TaskOpsDeleteParams) error
	// TaskOpsGet implements TaskOps_get operation.
	//
	// Get a task by ID.
	//
	// GET /tasks/{id}
	TaskOpsGet(ctx context.Context, params TaskOpsGetParams) (*Task, error)
	// TaskOpsList implements TaskOps_list operation.
	//
	// List all tasks for the authenticated user.
	//
	// GET /tasks
	TaskOpsList(ctx context.Context) (*TaskList, error)
	// TaskOpsUpdate implements TaskOps_update operation.
	//
	// Update a task.
	//
	// PATCH /tasks/{id}
	TaskOpsUpdate(ctx context.Context, req *UpdateTaskRequest, params TaskOpsUpdateParams) (*Task, error)
	// NewError creates *ApiErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ApiErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
