// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AuthOpsGetMe implements AuthOps_getMe operation.
	//
	// Get the currently authenticated user.
	//
	// GET /auth/me
	AuthOpsGetMe(ctx context.Context) (*UserProfile, error)
	// AuthOpsGoogleLogin implements AuthOps_googleLogin operation.
	//
	// Exchange Google ID token for a server-issued JWT.
	//
	// POST /auth/google
	AuthOpsGoogleLogin(ctx context.Context, req *GoogleAuthRequest) (*AuthResponse, error)
	// AuthOpsGoogleLoginWithCode implements AuthOps_googleLoginWithCode operation.
	//
	// Exchange Google authorization code for a server-issued JWT.
	//
	// POST /auth/google/code
	AuthOpsGoogleLoginWithCode(ctx context.Context, req *GoogleAuthCodeRequest) (*AuthResponse, error)
	// HealthOpsPing implements HealthOps_ping operation.
	//
	// Healthcheck endpoint.
	//
	// GET /ping
	HealthOpsPing(ctx context.Context) (*PingResponse, error)
	// StatusOpsCreate implements StatusOps_create operation.
	//
	// POST /statuses
	StatusOpsCreate(ctx context.Context, req *CreateStatusRequest) (*Status, error)
	// StatusOpsDelete implements StatusOps_delete operation.
	//
	// DELETE /statuses/{id}
	StatusOpsDelete(ctx context.Context, params StatusOpsDeleteParams) error
	// StatusOpsList implements StatusOps_list operation.
	//
	// GET /statuses
	StatusOpsList(ctx context.Context) (*StatusList, error)
	// StatusOpsUpdate implements StatusOps_update operation.
	//
	// PUT /statuses/{id}
	StatusOpsUpdate(ctx context.Context, req *UpdateStatusRequest, params StatusOpsUpdateParams) (*Status, error)
	// TagOpsCreate implements TagOps_create operation.
	//
	// POST /tags
	TagOpsCreate(ctx context.Context, req *CreateTagRequest) (*Tag, error)
	// TagOpsDelete implements TagOps_delete operation.
	//
	// DELETE /tags/{id}
	TagOpsDelete(ctx context.Context, params TagOpsDeleteParams) error
	// TagOpsList implements TagOps_list operation.
	//
	// GET /tags
	TagOpsList(ctx context.Context) (*TagList, error)
	// TagOpsUpdate implements TagOps_update operation.
	//
	// PUT /tags/{id}
	TagOpsUpdate(ctx context.Context, req *UpdateTagRequest, params TagOpsUpdateParams) (*Tag, error)
	// TaskOpsCreate implements TaskOps_create operation.
	//
	// Create a new task.
	//
	// POST /tasks
	TaskOpsCreate(ctx context.Context, req *CreateTaskRequest) (*Task, error)
	// TaskOpsDelete implements TaskOps_delete operation.
	//
	// Delete a task.
	//
	// DELETE /tasks/{id}
	TaskOpsDelete(ctx context.Context, params TaskOpsDeleteParams) error
	// TaskOpsGet implements TaskOps_get operation.
	//
	// Get a task by ID.
	//
	// GET /tasks/{id}
	TaskOpsGet(ctx context.Context, params TaskOpsGetParams) (*Task, error)
	// TaskOpsList implements TaskOps_list operation.
	//
	// List all tasks for the authenticated user.
	//
	// GET /tasks
	TaskOpsList(ctx context.Context) (*TaskList, error)
	// TaskOpsUpdate implements TaskOps_update operation.
	//
	// Update a task.
	//
	// PUT /tasks/{id}
	TaskOpsUpdate(ctx context.Context, req *UpdateTaskRequest, params TaskOpsUpdateParams) (*Task, error)
	// WishLabelOpsCreate implements WishLabelOps_create operation.
	//
	// POST /wish-labels
	WishLabelOpsCreate(ctx context.Context, req *CreateWishLabelRequest) (*WishLabel, error)
	// WishLabelOpsDelete implements WishLabelOps_delete operation.
	//
	// DELETE /wish-labels/{id}
	WishLabelOpsDelete(ctx context.Context, params WishLabelOpsDeleteParams) error
	// WishLabelOpsList implements WishLabelOps_list operation.
	//
	// GET /wish-labels
	WishLabelOpsList(ctx context.Context) (*WishLabelList, error)
	// WishLabelOpsUpdate implements WishLabelOps_update operation.
	//
	// PUT /wish-labels/{id}
	WishLabelOpsUpdate(ctx context.Context, req *UpdateWishLabelRequest, params WishLabelOpsUpdateParams) (*WishLabel, error)
	// WishOpsArchive implements WishOps_archive operation.
	//
	// POST /wishes/{id}/archive
	WishOpsArchive(ctx context.Context, params WishOpsArchiveParams) (*Wish, error)
	// WishOpsCreate implements WishOps_create operation.
	//
	// POST /wishes
	WishOpsCreate(ctx context.Context, req *CreateWishRequest) (*Wish, error)
	// WishOpsDelete implements WishOps_delete operation.
	//
	// DELETE /wishes/{id}
	WishOpsDelete(ctx context.Context, params WishOpsDeleteParams) error
	// WishOpsGet implements WishOps_get operation.
	//
	// GET /wishes/{id}
	WishOpsGet(ctx context.Context, params WishOpsGetParams) (*Wish, error)
	// WishOpsList implements WishOps_list operation.
	//
	// GET /wishes
	WishOpsList(ctx context.Context, params WishOpsListParams) (*WishList, error)
	// WishOpsUnarchive implements WishOps_unarchive operation.
	//
	// POST /wishes/{id}/unarchive
	WishOpsUnarchive(ctx context.Context, params WishOpsUnarchiveParams) (*Wish, error)
	// WishOpsUpdate implements WishOps_update operation.
	//
	// PUT /wishes/{id}
	WishOpsUpdate(ctx context.Context, req *UpdateWishRequest, params WishOpsUpdateParams) (*Wish, error)
	// NewError creates *ApiErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ApiErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
