// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	AuthOpsGetMeOperation               OperationName = "AuthOpsGetMe"
	AuthOpsGoogleLoginOperation         OperationName = "AuthOpsGoogleLogin"
	AuthOpsGoogleLoginWithCodeOperation OperationName = "AuthOpsGoogleLoginWithCode"
	PriorityOpsCreateOperation          OperationName = "PriorityOpsCreate"
	PriorityOpsDeleteOperation          OperationName = "PriorityOpsDelete"
	PriorityOpsListOperation            OperationName = "PriorityOpsList"
	PriorityOpsUpdateOperation          OperationName = "PriorityOpsUpdate"
	StatusOpsCreateOperation            OperationName = "StatusOpsCreate"
	StatusOpsDeleteOperation            OperationName = "StatusOpsDelete"
	StatusOpsListOperation              OperationName = "StatusOpsList"
	StatusOpsUpdateOperation            OperationName = "StatusOpsUpdate"
	TagOpsCreateOperation               OperationName = "TagOpsCreate"
	TagOpsDeleteOperation               OperationName = "TagOpsDelete"
	TagOpsListOperation                 OperationName = "TagOpsList"
	TagOpsUpdateOperation               OperationName = "TagOpsUpdate"
	TaskOpsCreateOperation              OperationName = "TaskOpsCreate"
	TaskOpsDeleteOperation              OperationName = "TaskOpsDelete"
	TaskOpsGetOperation                 OperationName = "TaskOpsGet"
	TaskOpsListOperation                OperationName = "TaskOpsList"
	TaskOpsUpdateOperation              OperationName = "TaskOpsUpdate"
)
