// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AuthOpsGetMe implements AuthOps_getMe operation.
//
// Get the currently authenticated user.
//
// GET /auth/me
func (UnimplementedHandler) AuthOpsGetMe(ctx context.Context) (r *UserProfile, _ error) {
	return r, ht.ErrNotImplemented
}

// AuthOpsGoogleLogin implements AuthOps_googleLogin operation.
//
// Exchange Google ID token for a server-issued JWT.
//
// POST /auth/google
func (UnimplementedHandler) AuthOpsGoogleLogin(ctx context.Context, req *GoogleAuthRequest) (r *AuthResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// AuthOpsGoogleLoginWithCode implements AuthOps_googleLoginWithCode operation.
//
// Exchange Google authorization code for a server-issued JWT.
//
// POST /auth/google/code
func (UnimplementedHandler) AuthOpsGoogleLoginWithCode(ctx context.Context, req *GoogleAuthCodeRequest) (r *AuthResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// HealthOpsPing implements HealthOps_ping operation.
//
// Healthcheck endpoint.
//
// GET /ping
func (UnimplementedHandler) HealthOpsPing(ctx context.Context) (r *PingResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// StatusOpsCreate implements StatusOps_create operation.
//
// POST /statuses
func (UnimplementedHandler) StatusOpsCreate(ctx context.Context, req *CreateStatusRequest) (r *Status, _ error) {
	return r, ht.ErrNotImplemented
}

// StatusOpsDelete implements StatusOps_delete operation.
//
// DELETE /statuses/{id}
func (UnimplementedHandler) StatusOpsDelete(ctx context.Context, params StatusOpsDeleteParams) error {
	return ht.ErrNotImplemented
}

// StatusOpsList implements StatusOps_list operation.
//
// GET /statuses
func (UnimplementedHandler) StatusOpsList(ctx context.Context) (r *StatusList, _ error) {
	return r, ht.ErrNotImplemented
}

// StatusOpsUpdate implements StatusOps_update operation.
//
// PUT /statuses/{id}
func (UnimplementedHandler) StatusOpsUpdate(ctx context.Context, req *UpdateStatusRequest, params StatusOpsUpdateParams) (r *Status, _ error) {
	return r, ht.ErrNotImplemented
}

// TagOpsCreate implements TagOps_create operation.
//
// POST /tags
func (UnimplementedHandler) TagOpsCreate(ctx context.Context, req *CreateTagRequest) (r *Tag, _ error) {
	return r, ht.ErrNotImplemented
}

// TagOpsDelete implements TagOps_delete operation.
//
// DELETE /tags/{id}
func (UnimplementedHandler) TagOpsDelete(ctx context.Context, params TagOpsDeleteParams) error {
	return ht.ErrNotImplemented
}

// TagOpsList implements TagOps_list operation.
//
// GET /tags
func (UnimplementedHandler) TagOpsList(ctx context.Context) (r *TagList, _ error) {
	return r, ht.ErrNotImplemented
}

// TagOpsUpdate implements TagOps_update operation.
//
// PUT /tags/{id}
func (UnimplementedHandler) TagOpsUpdate(ctx context.Context, req *UpdateTagRequest, params TagOpsUpdateParams) (r *Tag, _ error) {
	return r, ht.ErrNotImplemented
}

// TaskOpsCreate implements TaskOps_create operation.
//
// Create a new task.
//
// POST /tasks
func (UnimplementedHandler) TaskOpsCreate(ctx context.Context, req *CreateTaskRequest) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}

// TaskOpsDelete implements TaskOps_delete operation.
//
// Delete a task.
//
// DELETE /tasks/{id}
func (UnimplementedHandler) TaskOpsDelete(ctx context.Context, params TaskOpsDeleteParams) error {
	return ht.ErrNotImplemented
}

// TaskOpsGet implements TaskOps_get operation.
//
// Get a task by ID.
//
// GET /tasks/{id}
func (UnimplementedHandler) TaskOpsGet(ctx context.Context, params TaskOpsGetParams) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}

// TaskOpsList implements TaskOps_list operation.
//
// List all tasks for the authenticated user.
//
// GET /tasks
func (UnimplementedHandler) TaskOpsList(ctx context.Context) (r *TaskList, _ error) {
	return r, ht.ErrNotImplemented
}

// TaskOpsUpdate implements TaskOps_update operation.
//
// Update a task.
//
// PUT /tasks/{id}
func (UnimplementedHandler) TaskOpsUpdate(ctx context.Context, req *UpdateTaskRequest, params TaskOpsUpdateParams) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}

// WishLabelOpsCreate implements WishLabelOps_create operation.
//
// POST /wish-labels
func (UnimplementedHandler) WishLabelOpsCreate(ctx context.Context, req *CreateWishLabelRequest) (r *WishLabel, _ error) {
	return r, ht.ErrNotImplemented
}

// WishLabelOpsDelete implements WishLabelOps_delete operation.
//
// DELETE /wish-labels/{id}
func (UnimplementedHandler) WishLabelOpsDelete(ctx context.Context, params WishLabelOpsDeleteParams) error {
	return ht.ErrNotImplemented
}

// WishLabelOpsList implements WishLabelOps_list operation.
//
// GET /wish-labels
func (UnimplementedHandler) WishLabelOpsList(ctx context.Context) (r *WishLabelList, _ error) {
	return r, ht.ErrNotImplemented
}

// WishLabelOpsUpdate implements WishLabelOps_update operation.
//
// PUT /wish-labels/{id}
func (UnimplementedHandler) WishLabelOpsUpdate(ctx context.Context, req *UpdateWishLabelRequest, params WishLabelOpsUpdateParams) (r *WishLabel, _ error) {
	return r, ht.ErrNotImplemented
}

// WishOpsArchive implements WishOps_archive operation.
//
// POST /wishes/{id}/archive
func (UnimplementedHandler) WishOpsArchive(ctx context.Context, params WishOpsArchiveParams) (r *Wish, _ error) {
	return r, ht.ErrNotImplemented
}

// WishOpsCreate implements WishOps_create operation.
//
// POST /wishes
func (UnimplementedHandler) WishOpsCreate(ctx context.Context, req *CreateWishRequest) (r *Wish, _ error) {
	return r, ht.ErrNotImplemented
}

// WishOpsDelete implements WishOps_delete operation.
//
// DELETE /wishes/{id}
func (UnimplementedHandler) WishOpsDelete(ctx context.Context, params WishOpsDeleteParams) error {
	return ht.ErrNotImplemented
}

// WishOpsGet implements WishOps_get operation.
//
// GET /wishes/{id}
func (UnimplementedHandler) WishOpsGet(ctx context.Context, params WishOpsGetParams) (r *Wish, _ error) {
	return r, ht.ErrNotImplemented
}

// WishOpsList implements WishOps_list operation.
//
// GET /wishes
func (UnimplementedHandler) WishOpsList(ctx context.Context, params WishOpsListParams) (r *WishList, _ error) {
	return r, ht.ErrNotImplemented
}

// WishOpsUnarchive implements WishOps_unarchive operation.
//
// POST /wishes/{id}/unarchive
func (UnimplementedHandler) WishOpsUnarchive(ctx context.Context, params WishOpsUnarchiveParams) (r *Wish, _ error) {
	return r, ht.ErrNotImplemented
}

// WishOpsUpdate implements WishOps_update operation.
//
// PUT /wishes/{id}
func (UnimplementedHandler) WishOpsUpdate(ctx context.Context, req *UpdateWishRequest, params WishOpsUpdateParams) (r *Wish, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ApiErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ApiErrorStatusCode) {
	r = new(ApiErrorStatusCode)
	return r
}
