[tools]
go   = "1.26.1"
atlas = '1.1.0'
node = "24.14.0"
pnpm = "10.32.1"

"aqua:k1LoW/runn" = "1.6.0"

"go:github.com/ogen-go/ogen/cmd/ogen"  = "latest"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "latest"
"go:github.com/air-verse/air"          = "latest"

[tasks."db:migrate"]
description = "データベースのマイグレーションを実行します。"
run = "docker compose exec -T db psql -U postgres -d taskmanager < schema.sql && docker compose exec -T db psql -U postgres -d taskmanager_template < schema.sql"
