services:
  db:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - ./local/db/data:/var/lib/postgresql
      - ./schema.sql:/schema.sql:ro
      - ./local/db/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: "postgres://postgres:example@db:5432/taskmanager?search_path=taskmanager&sslmode=disable"
      PORT: "8080"
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app/api
    depends_on:
      db:
        condition: service_healthy
