// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: priorities.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createPriority = `-- name: CreatePriority :one
INSERT INTO priorities (user_id, name, display_order)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, display_order, created_at, updated_at
`

type CreatePriorityParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Name         string    `json:"name"`
	DisplayOrder int32     `json:"display_order"`
}

func (q *Queries) CreatePriority(ctx context.Context, arg CreatePriorityParams) (Priority, error) {
	row := q.db.QueryRow(ctx, createPriority, arg.UserID, arg.Name, arg.DisplayOrder)
	var i Priority
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePriority = `-- name: DeletePriority :exec
DELETE FROM priorities WHERE id = $1 AND user_id = $2
`

type DeletePriorityParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePriority(ctx context.Context, arg DeletePriorityParams) error {
	_, err := q.db.Exec(ctx, deletePriority, arg.ID, arg.UserID)
	return err
}

const getPriority = `-- name: GetPriority :one
SELECT id, user_id, name, display_order, created_at, updated_at FROM priorities WHERE id = $1 AND user_id = $2
`

type GetPriorityParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetPriority(ctx context.Context, arg GetPriorityParams) (Priority, error) {
	row := q.db.QueryRow(ctx, getPriority, arg.ID, arg.UserID)
	var i Priority
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPriorities = `-- name: ListPriorities :many
SELECT id, user_id, name, display_order, created_at, updated_at FROM priorities WHERE user_id = $1 ORDER BY display_order
`

func (q *Queries) ListPriorities(ctx context.Context, userID uuid.UUID) ([]Priority, error) {
	rows, err := q.db.Query(ctx, listPriorities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Priority
	for rows.Next() {
		var i Priority
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePriority = `-- name: UpdatePriority :one
UPDATE priorities SET
    name          = COALESCE($3,          name),
    display_order = COALESCE($4, display_order),
    updated_at    = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, display_order, created_at, updated_at
`

type UpdatePriorityParams struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	Name         *string   `json:"name"`
	DisplayOrder *int32    `json:"display_order"`
}

func (q *Queries) UpdatePriority(ctx context.Context, arg UpdatePriorityParams) (Priority, error) {
	row := q.db.QueryRow(ctx, updatePriority,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.DisplayOrder,
	)
	var i Priority
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
