// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statuses.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStatus = `-- name: CreateStatus :one
INSERT INTO statuses (id, user_id, name, display_order, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, display_order, created_at, updated_at
`

type CreateStatusParams struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Name         string             `json:"name"`
	DisplayOrder int32              `json:"display_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateStatus(ctx context.Context, arg CreateStatusParams) (Status, error) {
	row := q.db.QueryRow(ctx, createStatus,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.DisplayOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStatus = `-- name: DeleteStatus :exec
DELETE FROM statuses WHERE id = $1 AND user_id = $2
`

type DeleteStatusParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteStatus(ctx context.Context, arg DeleteStatusParams) error {
	_, err := q.db.Exec(ctx, deleteStatus, arg.ID, arg.UserID)
	return err
}

const getStatus = `-- name: GetStatus :one
SELECT id, user_id, name, display_order, created_at, updated_at FROM statuses WHERE id = $1 AND user_id = $2
`

type GetStatusParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetStatus(ctx context.Context, arg GetStatusParams) (Status, error) {
	row := q.db.QueryRow(ctx, getStatus, arg.ID, arg.UserID)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStatuses = `-- name: ListStatuses :many
SELECT id, user_id, name, display_order, created_at, updated_at FROM statuses WHERE user_id = $1 ORDER BY display_order
`

func (q *Queries) ListStatuses(ctx context.Context, userID uuid.UUID) ([]Status, error) {
	rows, err := q.db.Query(ctx, listStatuses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Status
	for rows.Next() {
		var i Status
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStatus = `-- name: UpdateStatus :one
UPDATE statuses SET
    name          = $3,
    display_order = $4,
    updated_at    = $5
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, display_order, created_at, updated_at
`

type UpdateStatusParams struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Name         string             `json:"name"`
	DisplayOrder int32              `json:"display_order"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (Status, error) {
	row := q.db.QueryRow(ctx, updateStatus,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.DisplayOrder,
		arg.UpdatedAt,
	)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
