// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, title, memo, due_date, status_id, priority_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, title, memo, due_date, status_id, priority_id, created_at, updated_at
`

type CreateTaskParams struct {
	UserID     uuid.UUID          `json:"user_id"`
	Title      string             `json:"title"`
	Memo       *string            `json:"memo"`
	DueDate    pgtype.Timestamptz `json:"due_date"`
	StatusID   uuid.UUID          `json:"status_id"`
	PriorityID uuid.NullUUID      `json:"priority_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.UserID,
		arg.Title,
		arg.Memo,
		arg.DueDate,
		arg.StatusID,
		arg.PriorityID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Memo,
		&i.DueDate,
		&i.StatusID,
		&i.PriorityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1 AND user_id = $2
`

type DeleteTaskParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.UserID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT
    t.id, t.user_id, t.title, t.memo, t.due_date, t.status_id, t.priority_id, t.created_at, t.updated_at,
    COALESCE(
        ARRAY_AGG(tt.tag_id) FILTER (WHERE tt.tag_id IS NOT NULL),
        '{}'
    )::uuid[] AS tag_ids
FROM tasks t
LEFT JOIN task_tags tt ON tt.task_id = t.id
WHERE t.id = $1 AND t.user_id = $2
GROUP BY t.id
`

type GetTaskParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetTaskRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Title      string             `json:"title"`
	Memo       *string            `json:"memo"`
	DueDate    pgtype.Timestamptz `json:"due_date"`
	StatusID   uuid.UUID          `json:"status_id"`
	PriorityID uuid.NullUUID      `json:"priority_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	TagIds     []uuid.UUID        `json:"tag_ids"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (GetTaskRow, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.UserID)
	var i GetTaskRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Memo,
		&i.DueDate,
		&i.StatusID,
		&i.PriorityID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TagIds,
	)
	return i, err
}

const insertTaskTag = `-- name: InsertTaskTag :exec
INSERT INTO task_tags (task_id, tag_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertTaskTagParams struct {
	TaskID uuid.UUID `json:"task_id"`
	TagID  uuid.UUID `json:"tag_id"`
}

func (q *Queries) InsertTaskTag(ctx context.Context, arg InsertTaskTagParams) error {
	_, err := q.db.Exec(ctx, insertTaskTag, arg.TaskID, arg.TagID)
	return err
}

const listTasks = `-- name: ListTasks :many
SELECT
    t.id, t.user_id, t.title, t.memo, t.due_date, t.status_id, t.priority_id, t.created_at, t.updated_at,
    COALESCE(
        ARRAY_AGG(tt.tag_id) FILTER (WHERE tt.tag_id IS NOT NULL),
        '{}'
    )::uuid[] AS tag_ids
FROM tasks t
LEFT JOIN task_tags tt ON tt.task_id = t.id
WHERE t.user_id = $1
GROUP BY t.id
ORDER BY t.created_at DESC
`

type ListTasksRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Title      string             `json:"title"`
	Memo       *string            `json:"memo"`
	DueDate    pgtype.Timestamptz `json:"due_date"`
	StatusID   uuid.UUID          `json:"status_id"`
	PriorityID uuid.NullUUID      `json:"priority_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	TagIds     []uuid.UUID        `json:"tag_ids"`
}

func (q *Queries) ListTasks(ctx context.Context, userID uuid.UUID) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksRow
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Memo,
			&i.DueDate,
			&i.StatusID,
			&i.PriorityID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TagIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTaskTags = `-- name: SetTaskTags :exec
DELETE FROM task_tags WHERE task_id = $1
`

func (q *Queries) SetTaskTags(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setTaskTags, taskID)
	return err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks SET
    title       = COALESCE($3,       title),
    memo        = COALESCE($4,        memo),
    due_date    = COALESCE($5,    due_date),
    status_id   = COALESCE($6,   status_id),
    priority_id = COALESCE($7, priority_id),
    updated_at  = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, memo, due_date, status_id, priority_id, created_at, updated_at
`

type UpdateTaskParams struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Title      *string            `json:"title"`
	Memo       *string            `json:"memo"`
	DueDate    pgtype.Timestamptz `json:"due_date"`
	StatusID   uuid.NullUUID      `json:"status_id"`
	PriorityID uuid.NullUUID      `json:"priority_id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Memo,
		arg.DueDate,
		arg.StatusID,
		arg.PriorityID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Memo,
		&i.DueDate,
		&i.StatusID,
		&i.PriorityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
