// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wish_labels.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createWishLabel = `-- name: CreateWishLabel :one
INSERT INTO wish_labels (user_id, name) VALUES ($1, $2) RETURNING id, user_id, name, created_at, updated_at
`

type CreateWishLabelParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) CreateWishLabel(ctx context.Context, arg CreateWishLabelParams) (WishLabel, error) {
	row := q.db.QueryRow(ctx, createWishLabel, arg.UserID, arg.Name)
	var i WishLabel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWishLabel = `-- name: DeleteWishLabel :exec
DELETE FROM wish_labels WHERE id = $1 AND user_id = $2
`

type DeleteWishLabelParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteWishLabel(ctx context.Context, arg DeleteWishLabelParams) error {
	_, err := q.db.Exec(ctx, deleteWishLabel, arg.ID, arg.UserID)
	return err
}

const getWishLabel = `-- name: GetWishLabel :one
SELECT id, user_id, name, created_at, updated_at FROM wish_labels WHERE id = $1 AND user_id = $2
`

type GetWishLabelParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetWishLabel(ctx context.Context, arg GetWishLabelParams) (WishLabel, error) {
	row := q.db.QueryRow(ctx, getWishLabel, arg.ID, arg.UserID)
	var i WishLabel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWishLabels = `-- name: ListWishLabels :many
SELECT id, user_id, name, created_at, updated_at FROM wish_labels WHERE user_id = $1 ORDER BY name
`

func (q *Queries) ListWishLabels(ctx context.Context, userID uuid.UUID) ([]WishLabel, error) {
	rows, err := q.db.Query(ctx, listWishLabels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WishLabel
	for rows.Next() {
		var i WishLabel
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWishLabel = `-- name: UpdateWishLabel :one
UPDATE wish_labels SET
    name       = $3,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, created_at, updated_at
`

type UpdateWishLabelParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

// PUT semantics: full replacement.
func (q *Queries) UpdateWishLabel(ctx context.Context, arg UpdateWishLabelParams) (WishLabel, error) {
	row := q.db.QueryRow(ctx, updateWishLabel, arg.ID, arg.UserID, arg.Name)
	var i WishLabel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
