// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wishes.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearWishLabels = `-- name: ClearWishLabels :exec
DELETE FROM wish_label_assignments WHERE wish_id = $1
`

func (q *Queries) ClearWishLabels(ctx context.Context, wishID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearWishLabels, wishID)
	return err
}

const createWish = `-- name: CreateWish :one
INSERT INTO wishes (user_id, title, detail) VALUES ($1, $2, $3) RETURNING id, user_id, title, detail, created_at, updated_at
`

type CreateWishParams struct {
	UserID uuid.UUID `json:"user_id"`
	Title  string    `json:"title"`
	Detail *string   `json:"detail"`
}

func (q *Queries) CreateWish(ctx context.Context, arg CreateWishParams) (Wish, error) {
	row := q.db.QueryRow(ctx, createWish, arg.UserID, arg.Title, arg.Detail)
	var i Wish
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWish = `-- name: DeleteWish :exec
DELETE FROM wishes WHERE id = $1 AND user_id = $2
`

type DeleteWishParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteWish(ctx context.Context, arg DeleteWishParams) error {
	_, err := q.db.Exec(ctx, deleteWish, arg.ID, arg.UserID)
	return err
}

const getWish = `-- name: GetWish :one
SELECT
    w.id, w.user_id, w.title, w.detail, w.created_at, w.updated_at,
    COALESCE(
        ARRAY_AGG(a.wish_label_id) FILTER (WHERE a.wish_label_id IS NOT NULL),
        '{}'
    )::uuid[] AS label_ids
FROM wishes w
LEFT JOIN wish_label_assignments a ON a.wish_id = w.id
WHERE w.id = $1 AND w.user_id = $2
GROUP BY w.id
`

type GetWishParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetWishRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Title     string             `json:"title"`
	Detail    *string            `json:"detail"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	LabelIds  []uuid.UUID        `json:"label_ids"`
}

func (q *Queries) GetWish(ctx context.Context, arg GetWishParams) (GetWishRow, error) {
	row := q.db.QueryRow(ctx, getWish, arg.ID, arg.UserID)
	var i GetWishRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LabelIds,
	)
	return i, err
}

const listWishes = `-- name: ListWishes :many
SELECT
    w.id, w.user_id, w.title, w.detail, w.created_at, w.updated_at,
    COALESCE(
        ARRAY_AGG(a.wish_label_id) FILTER (WHERE a.wish_label_id IS NOT NULL),
        '{}'
    )::uuid[] AS label_ids
FROM wishes w
LEFT JOIN wish_label_assignments a ON a.wish_id = w.id
WHERE w.user_id = $1
GROUP BY w.id
ORDER BY w.created_at DESC
`

type ListWishesRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Title     string             `json:"title"`
	Detail    *string            `json:"detail"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	LabelIds  []uuid.UUID        `json:"label_ids"`
}

func (q *Queries) ListWishes(ctx context.Context, userID uuid.UUID) ([]ListWishesRow, error) {
	rows, err := q.db.Query(ctx, listWishes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWishesRow
	for rows.Next() {
		var i ListWishesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Detail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LabelIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceWishLabels = `-- name: ReplaceWishLabels :exec
INSERT INTO wish_label_assignments (wish_id, wish_label_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type ReplaceWishLabelsParams struct {
	WishID  uuid.UUID   `json:"wish_id"`
	Column2 []uuid.UUID `json:"column_2"`
}

// PUT 全置換用。unnest で一括 INSERT。空配列でも安全（0 行 INSERT）。
func (q *Queries) ReplaceWishLabels(ctx context.Context, arg ReplaceWishLabelsParams) error {
	_, err := q.db.Exec(ctx, replaceWishLabels, arg.WishID, arg.Column2)
	return err
}

const updateWish = `-- name: UpdateWish :one
UPDATE wishes SET
    title      = $3,
    detail     = $4,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, detail, created_at, updated_at
`

type UpdateWishParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Title  string    `json:"title"`
	Detail *string   `json:"detail"`
}

// PUT semantics: full replacement. Client always sends title and detail
// (detail can be NULL to clear).
func (q *Queries) UpdateWish(ctx context.Context, arg UpdateWishParams) (Wish, error) {
	row := q.db.QueryRow(ctx, updateWish,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Detail,
	)
	var i Wish
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
