// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wishes.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveWish = `-- name: ArchiveWish :one
UPDATE wishes
SET archived_at = $3, updated_at = $3
WHERE id = $1 AND user_id = $2
RETURNING id
`

type ArchiveWishParams struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) ArchiveWish(ctx context.Context, arg ArchiveWishParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, archiveWish, arg.ID, arg.UserID, arg.ArchivedAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const clearWishLabels = `-- name: ClearWishLabels :exec
DELETE FROM wish_label_assignments WHERE wish_id = $1
`

func (q *Queries) ClearWishLabels(ctx context.Context, wishID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearWishLabels, wishID)
	return err
}

const createWish = `-- name: CreateWish :one
INSERT INTO wishes (id, user_id, title, detail, created_at, updated_at) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, user_id, title, detail, archived_at, created_at, updated_at
`

type CreateWishParams struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Title     string             `json:"title"`
	Detail    *string            `json:"detail"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateWish(ctx context.Context, arg CreateWishParams) (Wish, error) {
	row := q.db.QueryRow(ctx, createWish,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Detail,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Wish
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Detail,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWish = `-- name: DeleteWish :exec
DELETE FROM wishes WHERE id = $1 AND user_id = $2
`

type DeleteWishParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteWish(ctx context.Context, arg DeleteWishParams) error {
	_, err := q.db.Exec(ctx, deleteWish, arg.ID, arg.UserID)
	return err
}

const getWish = `-- name: GetWish :one
SELECT
    w.id, w.user_id, w.title, w.detail, w.archived_at, w.created_at, w.updated_at,
    COALESCE(
        ARRAY_AGG(a.wish_label_id) FILTER (WHERE a.wish_label_id IS NOT NULL),
        '{}'
    )::uuid[] AS label_ids
FROM wishes w
LEFT JOIN wish_label_assignments a ON a.wish_id = w.id
WHERE w.id = $1 AND w.user_id = $2
GROUP BY w.id
`

type GetWishParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetWishRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Title      string             `json:"title"`
	Detail     *string            `json:"detail"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	LabelIds   []uuid.UUID        `json:"label_ids"`
}

func (q *Queries) GetWish(ctx context.Context, arg GetWishParams) (GetWishRow, error) {
	row := q.db.QueryRow(ctx, getWish, arg.ID, arg.UserID)
	var i GetWishRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Detail,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LabelIds,
	)
	return i, err
}

const listWishes = `-- name: ListWishes :many
SELECT
    w.id, w.user_id, w.title, w.detail, w.archived_at, w.created_at, w.updated_at,
    COALESCE(
        ARRAY_AGG(a.wish_label_id) FILTER (WHERE a.wish_label_id IS NOT NULL),
        '{}'
    )::uuid[] AS label_ids
FROM wishes w
LEFT JOIN wish_label_assignments a ON a.wish_id = w.id
WHERE w.user_id = $1 AND w.archived_at IS NULL
GROUP BY w.id
ORDER BY w.created_at DESC
`

type ListWishesRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Title      string             `json:"title"`
	Detail     *string            `json:"detail"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	LabelIds   []uuid.UUID        `json:"label_ids"`
}

// 未アーカイブのみ
func (q *Queries) ListWishes(ctx context.Context, userID uuid.UUID) ([]ListWishesRow, error) {
	rows, err := q.db.Query(ctx, listWishes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWishesRow
	for rows.Next() {
		var i ListWishesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Detail,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LabelIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWishesIncludingArchived = `-- name: ListWishesIncludingArchived :many
SELECT
    w.id, w.user_id, w.title, w.detail, w.archived_at, w.created_at, w.updated_at,
    COALESCE(
        ARRAY_AGG(a.wish_label_id) FILTER (WHERE a.wish_label_id IS NOT NULL),
        '{}'
    )::uuid[] AS label_ids
FROM wishes w
LEFT JOIN wish_label_assignments a ON a.wish_id = w.id
WHERE w.user_id = $1
GROUP BY w.id
ORDER BY (w.archived_at IS NOT NULL), w.created_at DESC
`

type ListWishesIncludingArchivedRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Title      string             `json:"title"`
	Detail     *string            `json:"detail"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	LabelIds   []uuid.UUID        `json:"label_ids"`
}

// アーカイブ済みも含む全件。アーカイブ済みは末尾、未アーカイブは created_at DESC で並べる。
func (q *Queries) ListWishesIncludingArchived(ctx context.Context, userID uuid.UUID) ([]ListWishesIncludingArchivedRow, error) {
	rows, err := q.db.Query(ctx, listWishesIncludingArchived, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWishesIncludingArchivedRow
	for rows.Next() {
		var i ListWishesIncludingArchivedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Detail,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LabelIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceWishLabels = `-- name: ReplaceWishLabels :exec
INSERT INTO wish_label_assignments (wish_id, wish_label_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type ReplaceWishLabelsParams struct {
	WishID  uuid.UUID   `json:"wish_id"`
	Column2 []uuid.UUID `json:"column_2"`
}

// PUT 全置換用。unnest で一括 INSERT。空配列でも安全（0 行 INSERT）。
func (q *Queries) ReplaceWishLabels(ctx context.Context, arg ReplaceWishLabelsParams) error {
	_, err := q.db.Exec(ctx, replaceWishLabels, arg.WishID, arg.Column2)
	return err
}

const unarchiveWish = `-- name: UnarchiveWish :one
UPDATE wishes
SET archived_at = NULL, updated_at = $3
WHERE id = $1 AND user_id = $2
RETURNING id
`

type UnarchiveWishParams struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UnarchiveWish(ctx context.Context, arg UnarchiveWishParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, unarchiveWish, arg.ID, arg.UserID, arg.UpdatedAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateWish = `-- name: UpdateWish :one
UPDATE wishes SET
    title      = $3,
    detail     = $4,
    updated_at = $5
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, detail, archived_at, created_at, updated_at
`

type UpdateWishParams struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Title     string             `json:"title"`
	Detail    *string            `json:"detail"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// PUT semantics: full replacement. Client always sends title and detail
// (detail can be NULL to clear).
func (q *Queries) UpdateWish(ctx context.Context, arg UpdateWishParams) (Wish, error) {
	row := q.db.QueryRow(ctx, updateWish,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Detail,
		arg.UpdatedAt,
	)
	var i Wish
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Detail,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
