version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - bodyclose
    - errorlint
    - gocritic
    - misspell
    - nilerr
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - wrapcheck
  settings:
    wrapcheck:
      ignoreSigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - errors.Join(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
      ignorePackageGlobs:
        - task-manager/api/*
  exclusions:
    paths:
      - internal/api
      - internal/repository

formatters:
  enable:
    - gofmt
  exclusions:
    paths:
      - internal/api
      - internal/repository
