name: test-go

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install mise
        uses: jdx/mise-action@v4
        with:
          install: true
          cache: true

      - name: Docker Compose Up
        run: docker compose up -d --wait db
      - name: database initialize
        run: mise run db:migrate
      - name: go mod download
        run: cd api && go mod download

      - name: Run Tests
        run: cd api && go test -v ./...